/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fmontiel.calificaciones.views.materiasview;

import com.fmontiel.calificaciones.entities.Grado;
import com.fmontiel.calificaciones.entities.Materia;
import com.fmontiel.calificaciones.interfaces.CallbackInterface;
import com.fmontiel.calificaciones.models.GradosModel;
import com.fmontiel.calificaciones.models.MateriasModel;

import java.sql.SQLException;

import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author PC
 */
public class Formulario extends javax.swing.JFrame {

    private String nombre;
    private int id;

    private CallbackInterface onFinish;
    private Formulario.Modos modo;

    public static enum Modos {
        AGREGAR,
        EDITAR
    }

    public Formulario(
            Formulario.Modos modo,
            int id,
            String nombre,
            CallbackInterface onFinish) {
        this.id = id;
        this.modo = modo;
        this.nombre = nombre;
        this.onFinish = onFinish;

        initComponents();

        if (modo == Formulario.Modos.EDITAR) {
            textFieldNombre.setText(nombre);

            btnAccion.setText("Editar");
        }
    }

    public void add(Materia materia) throws SQLException {
        MateriasModel gm = new MateriasModel();
        boolean g = gm.existWithName(nombre);
        if (!g) {
            gm.addMateria(materia);

            this.textFieldNombre.setText("");

            onFinish.call(new JSONObject());
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe una sección con el mismo nombre y año");
        }

    }

    public void editar(Materia materia) throws SQLException {
        MateriasModel gm = new MateriasModel();
        /*
         * boolean g = gm.existWithName(textFieldNombre.getText());
         * 
         * if (g) {
         */
        gm.updateMateria(new Materia(id, textFieldNombre.getText()));

        this.nombre = this.textFieldNombre.getText();

        onFinish.call(new JSONObject());

        /*
         * } else {
         * JOptionPane.showMessageDialog(this, "No hay grados");
         * }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grados");

        btnAccion.setText("Agregar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaraccion(evt);
            }
        });

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAccion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldNombre)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 454,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizaraccion(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRealizaraccion

        try {
            if (Formulario.Modos.AGREGAR == modo) {
                add(new Materia(
                        0,
                        textFieldNombre.getText()));
            } else if (Formulario.Modos.EDITAR == modo) {
                editar(new Materia(
                        0,
                        textFieldNombre.getText()));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }

    }// GEN-LAST:event_btnRealizaraccion

    /**
     * @param args the command line arguments
     */
    /*
     * public static void main(String args[]) {
     * 
     * 
     * try {
     * for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) {
     * if ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName());
     * break;
     * }
     * }
     * } catch (ClassNotFoundException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (InstantiationException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (IllegalAccessException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * }
     * //</editor-fold>
     * 
     * 
     * java.awt.EventQueue.invokeLater(new Runnable() {
     * public void run() {
     * new Formulario().setVisible(true);
     * }
     * });
     * }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
