/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fmontiel.calificaciones.views.seccionesview;

import com.fmontiel.calificaciones.entities.Grado;
import com.fmontiel.calificaciones.interfaces.CallbackInterface;
import com.fmontiel.calificaciones.models.GradosModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author PC
 */
public class Formulario extends javax.swing.JFrame {

    private String nombre;
    private int anio;
    private char seccion;
    private CallbackInterface onFinish;
    private Formulario.Modos modo;

    public static enum Modos {
        AGREGAR,
        EDITAR
    }

    public Formulario(
            Formulario.Modos modo,
            String nombre,
            int anio,
            char seccion,
            CallbackInterface onFinish) {

        this.modo = modo;
        this.nombre = nombre;
        this.anio = anio;
        this.seccion = seccion;
        this.onFinish = onFinish;

        initComponents();

        textFieldNombre.setText(String.valueOf(seccion));
        this.btnAccion.setText("Editar");
    }

    public Formulario(
            Formulario.Modos modo,
            String nombre,
            int anio,
            CallbackInterface onFinish) {
        this.modo = modo;
        this.nombre = nombre;
        this.anio = anio;
        this.onFinish = onFinish;

        initComponents();

    }

    public void add(Grado grado) throws SQLException {
        GradosModel gm = new GradosModel();

        if (gm.firstWithNombreAndAnioAndSeccion(nombre, anio, grado.getSeccion()) == null) {
            gm.addGrado(grado);

            this.textFieldNombre.setText("");

            onFinish.call(new JSONObject());
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe una sección con el mismo nombre y año");
        }

    }

    public void editar(Grado grado) {
        GradosModel gm = new GradosModel();
        Grado g = gm.firstWithNombreAndAnioAndSeccion(nombre, anio, this.seccion);

        if (g != null) {
            gm.editSeccion(g.getId(), grado);

            this.nombre = grado.getNombre();
            this.anio = grado.getAnio();

            onFinish.call(new JSONObject());
        } else {
            JOptionPane.showMessageDialog(this, "No hay info");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Secciones");

        btnAccion.setText("Agregar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaraccion(evt);
            }
        });

        jLabel2.setText("Sección: (Ejemplo A, B, C)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAccion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldNombre)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 226,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAccion)
                                .addContainerGap(20, Short.MAX_VALUE)));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizaraccion(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRealizaraccion
        try {

            if (Formulario.Modos.AGREGAR == modo) {

                add(new Grado(
                        0,
                        nombre,
                        textFieldNombre.getText().charAt(0),
                        anio));

            } else if (Formulario.Modos.EDITAR == modo) {

                editar(new Grado(
                        0,
                        nombre,
                        textFieldNombre.getText().charAt(0),
                        anio));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_btnRealizaraccion

    /**
     * @param args the command line arguments
     */
    /*
     * public static void main(String args[]) {
     * 
     * 
     * try {
     * for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) {
     * if ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName());
     * break;
     * }
     * }
     * } catch (ClassNotFoundException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (InstantiationException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (IllegalAccessException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * }
     * //</editor-fold>
     * 
     * 
     * java.awt.EventQueue.invokeLater(new Runnable() {
     * public void run() {
     * new Formulario().setVisible(true);
     * }
     * });
     * }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
